### ISSUE TITLE
Nested tests fail

### ISSUE THREAD

**Issue by phorn-NI** [approvals/ApprovalTests.LabVIEW#2] opened 2024-09-17 14:49 UTC
I have a really simple test which passes
![image](https://github.com/user-attachments/assets/9bfaf769-a30a-406a-a12f-e83e3a4c9200)
However if I call that test from another vi, to group a bunch of tests together and run them all at once (as I often do with Caraya) it fails. Ignore the disconnected subvi with a vi reference input in the screenshot below - that is part of the workaround.
![image](https://github.com/user-attachments/assets/e785abd0-0da8-40e2-b878-787e1815a54c)
This is because its always looking for the top level vi thats called it for the name of the approved txt file, and so is looking at the red file in the box below instead of the green files
![image](https://github.com/user-attachments/assets/77ff14da-c628-49a3-b8da-99fcb7641062)
To work around it I've created a sub-vi that uses the test vi's reference to name the test correctly and then place this in every test. Not too bad but its not an ideal workaround as it requires remembering that in every test.
![image](https://github.com/user-attachments/assets/9d97be2a-9be1-4775-9eff-dc4fea14239e)

**Awesome toolkit though Sam - Thanks!!!**

**Comment by stagg54** [comment] 2024-09-17 15:58
Pete,
          Glad you like it. Glad you figured out the workaround. I don't use Caraya all that often and when I do its just simple tests, so I hadn't run into that yet. I agree doing that for every test is cumbersome. It probably should be builtin.I'll have to look into how best to fix it. I'll bring it up next time I pair with Llewelyn. You are welcome to come join us. We typically meet on Fridays around 10MT, so that would be Friday evening for you.
Sam

**Comment by stagg54** [comment] 2024-09-17 19:45
I was just able to reproduce it.

**Comment by stagg54** [comment] 2024-09-17 19:58
Think I've got it working. Even tested 2 levels of nesting and it appears to work fine.
I'll work on getting a new build out shortly.

**Comment by stagg54** [comment] 2024-09-17 19:58
![image](https://github.com/user-attachments/assets/89ef0a0e-e63d-46d1-928c-bc2b113a3264)

**Comment by stagg54** [comment] 2024-09-17 20:46
Also for the namer, the label is actually intended for something else. It's intended to allow multiple verifies in one test VI of the form

TestVIName.TestLabel.Approved.txt

**Comment by stagg54** [comment] 2024-09-17 21:02
Just released 2.2.5 on VIPM. Should solve your issue.

Let me know if it does (it should - it works on my machine and the CI server) and I'll close this issue.

If you give me your VIPM username I'll add you as a contributor on there.

If you like the project, don't forget to star it on VIPM.

Sam

**Comment by phorn-NI** [comment] 2024-09-18 07:53
> Also for the namer, the label is actually intended for something else. It's intended to allow multiple verifies in one test VI of the form
> 
> TestVIName.TestLabel.Approved.txt

Thanks, I was wondering how those two parameters were supposed to be used 👍 



> Just released 2.2.5 on VIPM. Should solve your issue.
> 
> Let me know if it does (it should - it works on my machine and the CI server) and I'll close this issue.
> 
> If you give me your VIPM username I'll add you as a contributor on there.
> 
> If you like the project, don't forget to star it on VIPM.
> 
> Sam

Wow - that was quick. I just tested it, works fine. Thanks for the rapid response. I just starred it on VIPM. My VIPM user name is peter_horn



> Pete, Glad you like it. Glad you figured out the workaround. I don't use Caraya all that often and when I do its just simple tests, so I hadn't run into that yet. I agree doing that for every test is cumbersome. It probably should be builtin.I'll have to look into how best to fix it. I'll bring it up next time I pair with Llewelyn. You are welcome to come join us. We typically meet on Fridays around 10MT, so that would be Friday evening for you. Sam

Sounds good - depending when it is on Friday evening (and whats happening with stuff at home) I might or might not be able to join. Can you send me an invite and I'll let you know closer to the time?

Cheers

**Comment by stagg54** [comment] 2024-09-18 17:48
I just found some freetime and it was easy enough to fix.

As to the mobbing/pairing sessions with LLewelyn, I'll add you to the list. Not sure when the next one will be. We were meeting pretty regularly, but lately we've both been doing the conference thing and travelling.

**Comment by stagg54** [comment] 2024-09-18 17:48
Closing this as it is confirmed fixed in release 2.2.5

**Closed by stagg54** 2024-09-18 17:48 UTC
